databases:
  - name: appointment
    databaseName: my_new_database_name # Change this to your new database name
    user: appointment_user

services:
  - type: web
    name: Barefoot
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appointment # This should match the name of the database service
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
